# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter
      - id: ruff-format

  # MyPy - Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - pandas-stubs
          - sqlalchemy[mypy]
        args: [--ignore-missing-imports, --check-untyped-defs]
        exclude: ^(tests/|notebooks/|alembic/|scripts/)

  # Bandit - Security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: ["bandit[toml]"]
        exclude: ^tests/

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(\.gitignore|\.coveragerc)$
      - id: end-of-file-fixer
        exclude: ^(\.gitignore|\.coveragerc)$
      - id: check-yaml
      - id: check-json
        exclude: ^terraform/
      - id: check-added-large-files
        args: [--maxkb=10000]
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  # Pytest with coverage check - runs locally using poetry
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest
        entry: poetry run pytest --tb=short -q
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: pytest-coverage
        name: pytest-coverage
        entry: poetry run pytest --cov --cov-fail-under=95 --tb=no -q
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
