"""initial schema

Revision ID: 213c78f7baa1
Revises: 
Create Date: 2025-10-08 16:43:50.012247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '213c78f7baa1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show_metadata',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('genres', mysql.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('network', sa.String(length=100), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('show_id')
    )
    op.create_table('show_similarities',
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.Column('similar_show_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('genre_score', sa.Float(), nullable=True),
    sa.Column('text_score', sa.Float(), nullable=True),
    sa.Column('metadata_score', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('show_id', 'similar_show_id')
    )
    op.create_index('idx_show_id', 'show_similarities', ['show_id'], unique=False)
    op.create_index('idx_similarity_score', 'show_similarities', ['show_id', 'similarity_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_similarity_score', table_name='show_similarities')
    op.drop_index('idx_show_id', table_name='show_similarities')
    op.drop_table('show_similarities')
    op.drop_table('show_metadata')
    # ### end Alembic commands ###
